from guardrails import Guard
from guardrails.hub import ValidLength


# =========================================================
# CREATE GUARDRAILS VALIDATOR
# =========================================================

# ValidLength checks whether the generated response
# is within an acceptable size.
#
# This prevents the LLM from returning an extremely
# short or extremely long answer.
try:

    guard = Guard().use(
        ValidLength(
            min=100,
            max=5000,
            on_fail="noop"
        )
    )

except Exception:

    # If the validator is unavailable, keep the
    # application from crashing.
    guard = None


# =========================================================
# VALIDATE AI OUTPUT
# =========================================================

def validate_output(
    text: str
) -> str:
    """
    Validate the response generated by Mistral.

    Parameters
    ----------
    text:
        Raw response generated by the Insight Agent.

    Returns
    -------
    str:
        Validated response.
    """

    # -----------------------------------------------------
    # CHECK EMPTY RESPONSE
    # -----------------------------------------------------

    if not text:

        return (
            "No response was generated."
        )


    # -----------------------------------------------------
    # GUARDRAILS NOT AVAILABLE
    # -----------------------------------------------------

    if guard is None:

        return text


    try:

        # -------------------------------------------------
        # RUN VALIDATION
        # -------------------------------------------------

        result = guard.parse(
            text
        )


        # -------------------------------------------------
        # CHECK VALIDATION RESULT
        # -------------------------------------------------

        if result.validation_passed:

            if result.validated_output:

                return str(
                    result.validated_output
                )

            return text


        # -------------------------------------------------
        # VALIDATION FAILED
        # -------------------------------------------------

        return (
            "The generated response did not "
            "pass the output validation."
        )


    except Exception:

        # Keep the application stable if the
        # validator itself encounters an error.
        return text